### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by jakajancar** [pelotom/runtypes#137]
Hey,

I saw in issue #129 @brandonkal ported runtypes to [Deno](https://deno.land):

https://github.com/brandonkal/runtypes

Could this be upstreamed? The big problem is renaming imports to `.ts`, not sure if this is feasible. An alternative might be to package a single-file bundle without any imports.

This would also make runtypes work in the browser.

**Comment by brandonkal** [comment]
I believe I opened another issue about this.

There were other issues getting the port to work besides changing imports such as ignoring some TypeScript issues.

That needs to be figured out before I'd make a PR here so if you want to speed this along, I would suggest OP make a PR against my fork figuring out why Deno required a few more ts-ignore comments and adding Deno-specific tests.

Because deno requires different imports, it would mean essentially duplicating all files in the repo or maintaining two master branches to maintain Deno + Node compat. For now it makes sense to maintain a separate repo fork as that makes tracking changes simple.

**Comment by jakajancar** [comment]
Yes, I can fix the issues properly vs. ignoring them, however, first I'd like to check if changing the imports to use a `.ts` suffix is even acceptable to the maintainers.

**Comment by brandonkal** [comment]
Until TypeScript itself accepts a proposal and merges in support for using that extension ESM imports and all the various bundlers follow suit we have to maintain two implementations. I am sure @pelotom  doesn't want to drop Node support anytime soon. This project is perfect for Deno because it has no node module dependencies. But for the foreseeable future this is where we are at.

**Comment by jakajancar** [comment]
Since there are now a couple of repos like Runtypes that I'd like to use, I created

https://stupid-extensions.com

Basically, just prepend to any URL to replace `import './foo'` in responses with `import './foo.ts'` (or .js):

This repo basically almost works out of the box, with one single error:

```
error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

► https://stupid-extensions.com/raw.githubusercontent.com/pelotom/runtypes/master/src/show.ts:65:9

65   throw Error('impossible');
```

Fixed in PR https://github.com/pelotom/runtypes/pull/138.

Meanwhile importable as

    import * as runtypes from 'https://stupid-extensions.com/raw.githubusercontent.com/jakajancar/runtypes/master/src/index.ts'

**Comment by brandonkal** [comment]
@jeremyBanks @jakajancar @yuhr I would like to see Deno runtime support merged in here.

I just updated my Deno fork for v6.0.0. You can see the changes required here: https://github.com/brandonkal/runtypes/commits/deno-v6

Much cleaner than what was required before. First of course is using extensions for imports and in the second commit on the branch you can see all the other changes required. Deno is isolatedModules by default and that was the bulk of it to get it to compile.

Also note that I was able to get most tests to pass when executed in Deno this time around with my jest-compat lib (an extension of expect). PRs to make https://x.kite.run/lib/testutils.ts more complete [here](https://github.com/brandonkal/expect/) would be appreciated. There were a few tests I disabled which will probably work with a `toMatchObject` method for Deno.

**Comment by yuhr** [comment]
Great work! So the barrier against merging it here is due to incompatibility of the testing framework?

**Comment by brandonkal** [comment]
Yes, jest is tied to node so it doesn't run in the Deno runtime. I'm not aware of a testing framework designed for both.

**Comment by AZMCode** [comment]
For the meantime, couldn't two testing frameworks be used separately?

**Comment by KnorpelSenf** [comment]
It may be worth considering to refactor the tests to use `Deno.test`. You can then use `dnt` to run the test suite on Node, too. That way, you have a single code base, double test coverage (one per platform) and massively improve testing speed while you're developing for Deno.

**Comment by KnorpelSenf** [comment]
Until then, we can actually directly use the main library (not a fork) via https://esm.sh like so:
```ts
import rt from "https://esm.sh/runtypes"; // don't forget to add a version
const {
  Array,
  Boolean,
  Literal,
  Number,
  Record,
  String,
  Tuple,
  Union,
} = rt;

const Vector = Tuple(Number, Number, Number);

console.log(Vector.validate('not a vector')))
```

**Comment by sant123** [comment]
I ported this library some time ago: https://github.com/sant123/runtypes 

All tests are passing and is ready to use. I'd highly appreciate your feedback.

**Comment by KnorpelSenf** [comment]
Amazing! Thank you, I'll use that for now.

In the long run, it would make a lot sense to unify the code bases again so that they do not diverge. If a bug is discovered and fixed here, you'll always need to sync up the repos manually. That is far from ideal. Having independent code prevents me from transferring the trust I have in the Node version to the Deno version.

Do you think you could look into dnt or deno2node and PR against this original project if you manage to produce the same build output?

**Comment by sant123** [comment]
That's something I could definitely do, however just want to make sure the maintainers of this repository are interested in that. Also want to highly the port doesn't support legacy decorators, this is intended since them will be deprecated when decorators proposal gets released and don't want to have code broken for the legacy stuff. So I prefer to support them when the are done.

**Comment by yuhr** [comment]
From my experience of using Deno for years, it seems to have become mature for Deno to work with npm modules, as [described in the official documentation](https://deno.com/manual/node). Back in the origin of Deno it was aimed to put Node.js stuff out of scope, but things changed. Now I feel like it's sufficient to use CDNs or `npm:` specifier to use this library in Deno.

I understand people might be facing some uncomfortable experience as [KnorpelSenf wrote above](https://github.com/pelotom/runtypes/issues/137#issuecomment-1019849428). But what I'm afraid of is, the versions already published on [`https://deno.land/x/runtypes`](https://deno.land/x/runtypes) is not the same as the ones on [`https://www.npmjs.com/package/runtypes?activeTab=versions`](https://www.npmjs.com/package/runtypes?activeTab=versions), and furthermore, I guess the official (npm) versions published prior to some point of time that we would set up [Webhooks](https://deno.com/add_module) wouldn't be available on `deno.land/x`. These inconsistencies could rather cause unexpected experience for existing users. A possible plan is to announce a “turning point” of the version history, e.g. from v7 we're going to be a Deno-first library and previous versions are not officially supported on Deno, ...but actually I'm in doubt if it's really worth it.

That said, I'd love to migrate the codebase to Deno-first and transpiling for Node.js using dnt. Publishing to registries is just optional (though I think [`nest.land`](https://nest.land) is okay for us).

**Comment by KnorpelSenf** [comment]
Being the author of a number of Deno-first libs, I can only encourage you to do the transition. Everything is just so much faster and simpler and easier and nicer.

What's your reason to avoid deno.land/x?

**Comment by yuhr** [comment]
I'm curious if having the inconsistencies I wrote above sounds good to you (and others). Just I haven't heard of libraries that have such history.

Another concern is, I'm not sure if it's possible to freely call the Webhooks endpoint to publish from multiple repositories, as currently it's been used by [sant123/runtypes](https://github.com/sant123/runtypes). I couldn't find any helpful documentation about what will happen in this case, but I don't think it's allowed as it would cause catastrophic situation, so probably we need to contact with the support, if we really want to do this.

Someone might suggest publishing under another name that isn't occupied, like `deno-runtypes`, but I never liked this style of UX ever. Why does it require me to type `deno-` to specify this Deno-first library published on `deno.land` in my Deno code? Because the canonical name `runtypes` is already used by someone. Blah. It's way better not to publish then.

**Comment by KnorpelSenf** [comment]
1. Publish the same version of the library under the same tag for all plattforms. It doesn't matter if many old versions are missing for Deno, it's more important that the more recent version has the same name on GitHub, /x, and npm.
2. It will be possible to communicate with @sant123 as well as the Deno team and make sure that this repo will contain the official build and that it will be the single source of truth for all plattforms. I'm sure they'll all be cooperative :)

**Comment by sant123** [comment]
@KnorpelSenf I’m open for this to give ownership for the name in deno.land/x and the project (the fork) itself if is required. Just let me know in how can I help.

**Comment by KnorpelSenf** [comment]
Thank you! I guess now it's upon @yuhr to decide how to move forward :)
