### ISSUE TITLE
"Better" support for nullable properties in Record?

### ISSUE THREAD

**Issue by spacepope** [pelotom/runtypes#15]
Hi,

at first i didn't know, how to declare nullable properties in a Record and if it is possible at all.
The only way i found so far is:
```
const A = Record({
  T: String,
  N: Number
}).And(Partial({
  Z: Boolean
}));
```
which results in a type:
```
type AType = {
    T: string;
    N: number;
} & {
    Z?: boolean;
}
```

Wouldn't it be more easy and intuitive if one could do:
```
const A = Record({
  T: String,
  N: Number,
  Z: Nullable(Boolean) // or Boolean.AsNullable()
  /*
       or even better as this is the normal typescript syntax?:
       Z?: Boolean
  */
});
```

Something like that shouldn't be that hard, or do i miss something?

Thanks and regards..

**Comment by pelotom** [comment]
Yes, the `Record.And(Partial)` is the current best practice for achieving this. I like the `Nullable` idea, unfortunately I'm pretty sure TypeScript's type system is insufficiently powerful to express it. 

Think about what the type signature would have to be for the `Record` type constructor in order to infer the right type as an output: you basically want to tell the type system to go through the value types and pick out the ones that were constructed with a special `Nullable` constructor, and for _just those_ the value type of the record should be optional.

I would be delighted to learn that there's a way to do this sort of thing, but AFAIK it's not possible :(

**Comment by spacepope** [comment]
Hmm, ok i see..
Would the following be a good or a bad idea:

There is already an Undefined and a Void runtype.
What if in Record code (Line 19) is only checked for key existance if the value is not of type Undefined or Void?
So one could define an optional record property with  `NullableProperty: Number.Or(Void)`..
What do you think?

**Comment by pelotom** [comment]
Allowing keys to be missing if their corresponding value types are `null` or `undefined` is inconsistent with the static type semantics of typescript:

```ts
const foo: { x: null | undefined } = {}
//    ^^^
// Type '{}' is not assignable to type '{ x: null | undefined; }'.
//  Property 'x' is missing in type '{}'.
```

**Comment by spacepope** [comment]
To correct myself: i was rather speaking of optional than nullable properties..
But as it seems (and besides your comment) one cannot selectively pick properties from an underlying type filtered to the value type. And if it would be possible, it probably results in the union of non optional and optional parameters too, so i can live with the way it works..
