### ISSUE TITLE
How to construct a Record with given keys and type, similar to TypeScripts's Record<K, T>?

### ISSUE THREAD

**Issue by Remirror-zz** [pelotom/runtypes#160]
Hello! Sorry if this is a basic question but I couldn't find the answer.

Input:
```
const WeekDay = Union(
    Literal('monday'),
    Literal('tuesday'),
    Literal('wednesday'),
    Literal('thursday'),
    Literal('friday'),
    Literal('saturday'),
    Literal('sunday')
);
const OpeningHoursForDay = Record({
    'from': Number,
    'to': Number,
});
```
Desired output (without having to repeat each day literally):
```
Record({
    'monday': OpeningHoursForDay,
    'tuesday': OpeningHoursForDay,
    ...
});
```
Approach similar to:
`const OpeningHoursForWeekT = .....?.....(WeekDay, OpeningHoursForDay);`
Analogously to TypeScript:
`type OpeningHoursForWeekT = Record<WeekDay, OpeningHoursForDay>;`

(How) can this be done?

**Comment by KingDarBoja** [comment]
I think this can be archieved by using [Dictionary](https://github.com/pelotom/runtypes/blob/master/src/types/dictionary.ts) as stated at #143. 

Should be great to have this one documented as well.

**Comment by Remirror-zz** [comment]
Thanks, but I don't see how this works; can you elaborate on it a bit?

If I just try `const OpeningHoursForWeekT = Dictionary(OpeningHoursForDay);`, I get a `Record<string, OpeningHoursForDay>` rather than the desired `Record<WeekDay, OpeningHoursForDay>`, so any key would be accepted.

**Comment by KingDarBoja** [comment]
```ts
import * as rt from 'runtypes';

function getObjectMap<T extends string, U>(union: { alternatives: rt.Literal<T>[] }, value: U) {
  return union.alternatives.reduce((acc, val) => {
    // not totally sure why the cast is necessary here
    (acc as any)[val.value] = val.value;
    return acc;
  }, {} as { [K in T]: U });
}

const WeekDay = rt.Union(
  rt.Literal('monday'),
  rt.Literal('tuesday'),
  rt.Literal('wednesday'),
  rt.Literal('thursday'),
  rt.Literal('friday'),
  rt.Literal('saturday'),
  rt.Literal('sunday')
);
const OpeningHoursForDay = rt.Record({
  from: rt.Number,
  to: rt.Number,
});

const OpeningHoursForWeek = rt.Record(getObjectMap(WeekDay, OpeningHoursForDay));

type OpeningHoursForWeek = rt.Static<typeof OpeningHoursForWeek>;
```

**Comment by Remirror-zz** [comment]
Ah I see, this works, thank you!

However, I wonder about the line `(acc as any)[val.value] = val.value;`. In my case (in contrast to the original post in #79 ), it still works when I comment out this line, so one can reduce the function to:
```
function getObjectMap<T extends string, U>(union: { alternatives: rt.Literal<T>[] }, value: U) {
  return union.alternatives.reduce((acc, val) => acc, {} as { [K in T]: U });
}
```
Now I wonder whether this could be written in one line (or rather without a function but only concretely for WeekDay and OpeningHoursForDay), but I did not succeed yet.

**Comment by KingDarBoja** [comment]
I think that can be done by providing a custom dictionary constructor like the library does but providing a second argument (or third in this case) for the key.

https://github.com/pelotom/runtypes/blob/master/src/types/dictionary.ts

Something like below (this code is a draft):

```ts
export interface StringDictionary<V extends Runtype, U> extends Runtype<{ [_: key in U]: Static<V> }> {
  tag: 'dictionary';
  key: K in U;
  value: V;
}

export function Dictionary<V extends Runtype>(value: V, keys: U): StringDictionary<V, U>;
```

**Comment by schicks** [comment]
@Remirror-zz, I'm not sure I understand your function. it seemed to me that it didn't make sense that the `value` argument was unused, so I tried some fiddling and rewrote the function to this; 

```typescript
function KeyedDictionary<T extends string, U>(
  union: { alternatives: Literal<T>[] },
  value: Runtype<U>
): Runtype<{ [K in T]: U }> {
  const objectMap =  union.alternatives.reduce<{ [K in T]?: Runtype<U> }>((acc, val) => {
    return {
      ...acc,
      [val.value]: value
    }
  }, {}) as { [K in T]: Runtype<U> };
  return Record(objectMap)
}
```

this gets rid of the any casting and actually assigns the value type to each key in the union. I'm not sure how the other version would have worked; did you test the runtype behavior or just see that the result had the correct type?

**Comment by Remirror-zz** [comment]
@schicks Good catch! I also wondered about `value` not being used, but the compiler did not complain, so I thought maybe it is just needed because of its type (U). I did a few quick tests, but you are right: When I e.g. try to parse JSON and use `OpeningHoursForWeek.check()` on the parsed object, it will accept the object regardless of whether it is compliant with the type specification or not. When I use your function, the check correctly refutes misspecified objects. 

The approach of @KingDarBoja with a new interface may also work I think.

**Comment by bayareacoder** [comment]
@schicks If you’re returning a Record for a KeyedDictionary then validation will pass for additional keys that are not in the dictionary which is not the intent of a dictionary. 
I think @KingDarBoja approach is correct, but requires additions  to Dictionary.ts to fail when a non-specified key is found on the object.

**Comment by bayareacoder** [comment]
@schicks Returning a `Record` for a `KeyedDictionary` will cause validation to pass if the object has keys that are not in the dictionary. That's not the intent of a dictionary. I think @KingDarBoja 's approach is correct but it requires a change to the `Dictionary` method in the library so that it fails validation if a key is found that is not in the list of specified keys.

My use case is to check and fail validation if a Record has additional properties beyond required and optional ones. The only way to do that is to intersect 1/ `Record({..{}).And(Partial({...})` with 2/ a keyed dictionary that has all required + optional keys and a type of Unknown. 1/ will check that all required keys are present, and all required + optional keys have the correct type. 2/ will check that no additional keys are present.

**Comment by yuhr** [comment]
Once #193 get released, you can pass a `Union` as `Dictionary` key type:
```ts
const WeekDay = Union(
  Literal("monday"),
  Literal("tuesday"),
  Literal("wednesday"),
  Literal("thursday"),
  Literal("friday"),
  Literal("saturday"),
  Literal("sunday")
)
const OpeningHoursForDay = Record({
  from: Number,
  to: Number,
})

const DesiredOutput = Dictionary(OpeningHoursForDay, WeekDay)
type DesiredOutput = Static<typeof DesiredOutput>
// type DesiredOutput = {
//     monday: {
//         from: number;
//         to: number;
//     };
//     tuesday: {
//         from: number;
//         to: number;
//     };
//     wednesday: {
//         from: number;
//         to: number;
//     };
//     thursday: {
//         from: number;
//         to: number;
//     };
//     friday: {
//         from: number;
//         to: number;
//     };
//     saturday: {
//         from: number;
//         to: number;
//     };
//     sunday: {
//         ...;
//     };
// }
```

**Comment by bayareacoder** [comment]
How does this solve the use case in my original post where you have different types for each key, and some keys are optional vs others required,  which I currently code as follows:
```
const allowedKeys = ['requiredKey1', 'requiredKey2','optionalKey3'] as const;
const MyRunType = Record({
  requiredKey1 : Boolean,
  requiredKey2: Number,
}).And(Partial({
  optionalKey3: String
}).And(Dictionary(Unknown, allowedKeys);
```
It seems the above solution only seems to work if the value of each key is of the same type?

**Comment by yuhr** [comment]
`Dictionary` is not supposed to be used for such a complex use case, just think of it as a similar thing to TypeScript's built-in `Record<K, V>` or ES6 `Map<K, V>`. I'd rather append some fundamental functionalities to `Record`, to support rest properties #201 and exact match #41. Once they're implemented, `Dictionary` would come to the end of its life or just become an alias to `Record`. Furthermore, I have some hesitation to allow arguments like `{ optional: true }`, because it provides one more extra additional duplicate API to do that instead of `.asPartial()` and `Optional(...)` and `.Partial(...)`.

Anyway, I believe your point is how to achieve exact validation, with some specific keys and some unknown keys. Let's track this at #201 and #41.

**Comment by bayareacoder** [comment]
The issue is to have validation with keys that are required, and other keys that are optional, while making sure there are no extra keys. Even in the latest release, I don't see how it can be done in any other way than in my original code which requires specifying each key twice and results in non-clean TS typings

```
const allowedKeys = ['requiredKey1', 'requiredKey2','optionalKey3'] as const;
const MyRunType = Record({
  requiredKey1 : Boolean,
  requiredKey2: Number,
}).And(Partial({
  optionalKey3: String
}).And(Dictionary(Unknown, allowedKeys);
```

The use case is to very that an API client and API server are matched: 
- all API client TS types correspond to what API server provides
- no keys expected by API client are missing from API server
- API server does not provide extra keys/values which are not included in the API client's typings

**Comment by yuhr** [comment]
Oh, sorry, I was misreading your example code (and my bad, I see #201 is not related here 🤣). In your case, the intersection with `Partial` can be replaced with `Optional`. For example:

```ts
const allowedKeys = Union(Literal('requiredKey1'), Literal('requiredKey2'), Literal('optionalKey3'));
const MyRunType = Record({
  requiredKey1: Boolean,
  requiredKey2: Number,
  optionalKey3: Optional(String)
}).And(Dictionary(Unknown, allowedKeys);
```

This is already possible in v5.2.0. And now I've realized why you intersect `Dictionary` here, it is just to achieve exact validation (disallow unknown properties) right? So once we have introduced exact validation to `Record`, then you'll be able to remove the last intersection and get a clean static type like:

```ts
{
    requiredKey1: boolean;
    requiredKey2: number;
    optionalKey3?: string;
}
```

As I commented here https://github.com/pelotom/runtypes/issues/127#issuecomment-805429786, I'm not thrilled with combining properties of intersected object types, simply because TS doesn't do that. You should use `Optional` if you want to see clean types instead of `{...} & {...}`.

**Comment by bayareacoder** [comment]
@yuhr thanks. That is a good suggestion. Now only 1 instead of 2 intersections. And hopefully soon 0 when you have exact match on Record (with support for known optional keys). Indeed the extra Dictionary is to disallow additional keys.

**Comment by yuhr** [comment]
Hmm, you're correct. It's not working properly when trying to declare variables with the type, sorry again.

> Note that the generated TS type already suggests that you should not need the Dictionary. It would already fail in TS with any extra key from only the converted Record type (at least if you assign an object literal). 

Yes, that's one of the reasons why I proposed [this](https://github.com/pelotom/runtypes/issues/41#issuecomment-812745094). It must be reasonable to change behavior of `check`, mirroring TS. I think this would come in v7 😉
