### ISSUE TITLE
cannot use Static in *.d.ts file

### ISSUE THREAD

**Issue by nrobin24** [pelotom/runtypes#21]
I'd really like to be able to define my types in runtypes, and then use the `type MyType = Static<typeof MyType>` feature, but I cannot figure out how to incorporate this into my project

The examples show this all being done in one file, but what if I have a `types.d.ts` file in my project where I am declaring the types that are shared throughout multiple files? I tried importing the runtypes that I declared and the `Static` function into my `types.d.ts` file and then declaring the type there, but that seemed to make my d.ts file invalid.

Any ideas?

Thanks in advance and thanks for this project.

**Comment by pelotom** [comment]
The only way I know to make this work is by using `declare global`, like this:

```ts
import { Number, String, Literal, Record, Union2, Static } from 'runtypes'

export const Foo = Record({
    a: Number,
    b: String,
    c: Literal('x').Or(Literal('y')),
})

declare global {
    type Foo = Static<typeof Foo>
}
```

Then in another module you can use

```ts
const foo: Foo = {...}
```

**Comment by nrobin24** [comment]
Thanks I will give that a try.

Interestingly after messing around I found another solution that works, although you have to explicitly import the types you want to use

I can have one file where I do:

```
export const MyType = Record({a: Number})

export type MyType = Static<typeof MyType>
```

and then in the file where I am using both the type and runtype, I can use a single import statement

```
import {MyType} from './myType'

const bla: MyType = something()

MyType.check(bla)
```

and TypeScript can figure out where I am using the type and where I am using the runtype

**Comment by pelotom** [comment]
Oh, yes! That's very much how it's intended to be used 😄.  I thought you required a solution where the static types were ambiently available globally without having to be imported, but I think this is generally a much better approach.

**Comment by jeremyBanks** [comment]
Not quite related, but I wanted to share a tangential point that I didn't realize until after seeing this thread: if you import a module that defines runtypes, but only reference the static types, not the run-time validators, TypeScript will remove the import in the compiled code! That means that you can use the runtime static types even when you don't have the runtime support.

In my case, I have a TypeScript code base that's partially shared between client and server. Node modules like runtypes are only supported on the server (since I'm not using something like webpack to get them on the client), but my client code can still import the runtypes static types without issue. This realization made runtypes much more practical for me.
