### ISSUE TITLE
Type that represents anonymous function definition

### ISSUE THREAD

**Issue by jackflap** [pelotom/runtypes#250]
I'm trying to create a data structure which stores anonymous functions (i.e. lambdas / arrow functions), and validates the inputs/outputs.

I'm struggling to figure out whether this is possible, and what the syntax might be.

If I were to define the anonymous function as I would in regular TypeScript, I would do something like the following:
```
export const MultiStatisticsWidget = Record({
    widgetType: WidgetType,
    widgetName: String,
    widgetPeriod: Number,
    defaultMetric: String,
    thresholds: (enabled: Boolean) => Number
});

export type MultiStatisticsWidget = Static<typeof MultiStatisticsWidget>;

const widget: MultiStatisticsWidget = {
    widgetType: "TEST",
    widgetName: "test",
    defaultMetric: "Test",
    widgetPeriod: 5,
    thresholds: (enabled: Boolean) => enabled ? 10 : 0
}
```
But it gives me the error: TS2740: Type '(enabled: Boolean) => Number' is missing the following properties from type 'Runtype<unknown>': assert, check, validate, guard, and 7 more.

It looks like Function might work, but there doesn't seem to be any way to validate that it takes a Boolean as an input and a Number as an output. I've also played around with Contract, but it doesn't seem to like being made into a Type.

Is there anything obvious that I'm missing?

**Comment by yuhr** [comment]
Yeah, `Contract` is not meant to validate functions, but their arguments and return values at call time. If we have #191 merged, then you will be able to convert validated functions into their `Contract`-wrapped versions automatically.

The problem is, JavaScript has no runtime reflection/introspection about the signature of a function. So unfortunately there's no chance to be able to validate genuinely parameters' types and return types of provided functions. If you *really* want to do that, then you need to implement some reflection feature on your own, for example, "embed" necessary information into your functions, and validate those information instead of the function itself, like this:

```ts
const f = Object.assign({ returns: 'boolean' } as const, () => true);
Record({ returns: Literal('boolean') }).validate(f);
```

But I don't think it's a good idea. It would easily become disgusting if developers have to populate such properties opaquely in order to create legal functions. Furthermore, newly-created values that need to be validated against your schema are basically coming from outside of your control, and you cannot expect those properties are already populated.

**Comment by jackflap** [comment]
Thanks for the response - that makes sense.
