### ISSUE TITLE
In the latest runtypes 6.3.0 version is there a support for it can be Optional, it can be null Ex: Optional(String.nullable())

### ISSUE THREAD

**Issue by samathan** [pelotom/runtypes#251]
Hi,

Last week I have upgraded runtypes from 5.1.0 to 6.3.0 .

Due to update made changes to the existing code like if there is 
String.Or(Undefined) changed to Optional(String) , 
Boolean.Or(Undefined) changes to Optional(Boolean) .
Please correct me if I am wrong with the above and also please advice me the best way for the above.

Now my question is there a support like it can be optional or it can be null as well like Optional(String.nullable()) ?

And also last but not least, I saw there is an update to the ReadMe as well, says as below, does that mean are there any plans to remove Partial? Because I are using Partial in quite a few places.

_The last syntax is not any shorter than writing Optional(String) when you import Optional directly from runtypes, but if you use scoped import i.e. import * as rt from 'runtypes', it would look better to write rt.String.optional() rather than rt.Optional(rt.String).

If a Record may or may not have some properties, we can declare the optional properties using Record({ x: Optional(String) }) **(or formerly Partial({ x: String })).** Optional properties validate successfully if they are absent or undefined or the type specified.

// Using `Ship` from above
const RegisteredShip = Ship.And(
  Record({
    // All registered ships must have this flag
    isRegistered: Literal(true),

    // We may or may not know the ship's classification
    shipClass: Optional(Union(Literal('military'), Literal('civilian'))),

    // We may not know the ship's rank (so we allow it to be undefined via `Optional`),
    // we may also know that a civilian ship doesn't have a rank (e.g. null)
    rank: Optional(Rank.Or(Null)),
  }),
);_

Thank you so much for providing a wonderful runtypes module.

Regards,
Samatha

**Comment by yuhr** [comment]
> Please correct me if I am wrong with the above and also please advice me the best way for the above.

You're doing right thing there. Note that `String.Or(Undefined)` in `Record` is not optional anymore due to the breaking change introduced in v6.

> Now my question is there a support like it can be optional or it can be null as well like Optional(String.nullable()) ?

I'm not sure I understand what you're asking about. `Optional(String.nullable())` should work as you intended.

> And also last but not least, I saw there is an update to the ReadMe as well, says as below, does that mean are there any plans to remove Partial? Because I are using Partial in quite a few places.

Speaking from my personal desire, yes, I want to deprecate `Partial(...)` from public APIs in favor of `Record(...).asPartial()`, and change the behavior of them to just wrapping every field with `Optional`, but it won't be any time soon. Maybe such changes come in v8 or the like.

**Comment by KingDarBoja** [comment]
> Now my question is there a support like it can be optional or it can be null as well like Optional(String.nullable()) ?

Been using `rt.String.nullable().optional()` for a while and seems to work as expected. I think what you want is a shorter version, right?

**Comment by yuhr** [comment]
We won't provide any shorthand for `.nullable().optional()`, because `Optional` has a different semantics than the other in the context of `Record`, and users should be aware of that by writing that explicitly each time.

By the way if you want to unionize `Null` and `Undefined` (not `Optional`), then you can use `Nullish`:

```ts
String.Or(Nullish)
```
