### ISSUE TITLE
Is it possible with current API to get value for field from another field of schema(record)?

### ISSUE THREAD

**Issue by daklin2** [pelotom/runtypes#258]
Hi, have a condition on which depend my type for field, but in this condition i should check value which is another field of my schema, is it possible to take value of this field?

example: 
```
const sch = Record({
  animals: Union(Literal("dog"), Literal("fox"))
  dogs: String // should be required if animals == dog and if not then optional  
}) 
```
No matter if it will manual check with constraint or condition for actually type

The only way i found without rewriting lib is with constraint for entire schema, but in this way i can't return path to my field in **schema.validation(values)**, it's just return message 

It was something like that:
```
const noEmpty = String.withConstraint((v) => !!v.length || "Required");
const sch = Record({
  animals: Union(Literal("dog"), Literal("fox"))
  dogs: String // should be required if animals == dog and if not then optional  
}).withConstraint((v) => {
  if(v.animals === dog) {
    const valid = noEmpty(v.dogs)
    return valid.succes || "Requred"
  }
}
```

Maybe there a way to return fully custom error from constraint? Or maybe there way to achieve it somehow another?

**Comment by yuhr** [comment]
In that case, your type can be expressed without "conditions", and there has to be just two "patterns", so I would prescribe the schema like this:

```ts
const sch = Union(
  Record({ animals: Literal('dog'), dogs: String }),
  Record({ animals: Literal('fox'), dogs: Optional(String) }),
);
```

I recommend you think `Constraint` should only be used as the escape hatch when the desired set of values cannot be expressed in TS's type system e.g. integer numbers, regex-generated strings, etc., and as you see, such types are generally subtypes of *primitive* types, not complex (object) types. I can't imagine any case `Constraint` is effectively used along with `Record`.

**Comment by daklin2** [comment]
Thanks so much for so fast answer :)
Yeah, it can be solution
Just have 2 moments to discuss 

1. What about performance? As i understand It's will provide badly performance as its will need to check few different scheme for compare, i'm right?
If yes, maybe there is some less expensive method? Just have pretty extended scheme, and performance is what i'm fighting for now 

2. It's some aside question, struggle with behavior of **Union**
As i understand If i create Union inside of Union it's broke validation: _"Expected {...} but was object"_
It's predicted behavior and can be replaced with right Types or a bug?

Example: 
```
const sch = Union(
  Record({ animals: Literal('dog'), dogs: String }),
  Record({ animals: Union(Literal('fox'), Literal("cat)), dogs: Optional(String) }),
)

sch.validate(values) --> "Expected {...} but was object"
```

**Comment by yuhr** [comment]
1. If you have a ton of properties, yes, it's a reasonable concern as well. I think you could split your schema into two parts then: a 'Union' of 'Record's which only contain the literal field and the relevant, and another 'Record' which contains other common fields. Since 'Record' validation is not exhaustive[^1], you can test your unknown objects against just one part of properties, depending on what properties are needed in your particular code flow. If you need both everywhere, just intersect them. This way the performance problem should be gone.

2. That must be a bug, see #216. Current implementaion of 'Union' has a quite heuristic code path for "discriminated unions" or "tagged unions" (#67), and error messages will only work in some cases. This needs a solution definitely but I'm not sure how it can be... Any help for this is appreciated.

[^1]: Though the default behavior may change in the future. Please subscribe to #41 to see updates.

**Comment by yuhr** [comment]
Closing as inactive, please reopen if you have further questions.
