### ISSUE TITLE
Problems with typescript 4.5

### ISSUE THREAD

**Issue by dfilatov** [pelotom/runtypes#290]
Hi!
First of all, thank you for your beautiful library we're using extensively in our projects.

Today I've tried to upgrade typescript from 4.4.4 to 4.5.2 in our project and got fail with runtypes.

Minimal case to reproduce:
```ts
function test<TParams extends runtypes.Record<{}, false>>(params: TParams): void {}

test(runtypes.Record({ param: runtypes.String }));
```

Error:
```
Argument of type 'Record<{ param: String; }, false>' is not assignable to parameter of type 'Record<{}, false>'.
  The types returned by 'asPartial().asReadonly()' are incompatible between these types.
    Type 'InternalRecord<{ param: String; }, true, true>' is not assignable to type 'InternalRecord<{}, true, true>'.
      Type '{}' is not assignable to type '{ param: runtypes.String; }'.ts(2345)
```

**Comment by dfilatov** [comment]
@yuhr Hi, Yu! Could you take a look?

**Comment by yuhr** [comment]
Sorry for the absence, I'll take a look tomorrow 💦

**Comment by yuhr** [comment]
@dfilatov Hm, we're very sorry this has never been documented, but generally it's recommended to avoid using the interfaces such as `Record` directly as a type bound, and instead you should use `Runtype<...>`. If I understand your intention correctly, using `TParams extends Runtype<object>` should work, since `object` type is exactly for filtering out any types other than plain object. For instance:

```ts
function test<TParams extends runtypes.Runtype<object>>(params: TParams): void {}
test(runtypes.Record({ param: runtypes.String })); // Accepted
test(runtypes.String); // Type 'string' is not assignable to type 'object'.
```

**Comment by dfilatov** [comment]
@yuhr Thank you for advice!
`runtypes.Runtype<object>` doesn't fit us in more complex case but `runtypes.Runtype<Record<string, unknown>>` does.
