### ISSUE TITLE
How check for ObjectId?

### ISSUE THREAD

**Issue by 205g0** [pelotom/runtypes#312]
Not sure if I missed something in the docs but how would I check for MongoDB's `ObjectId`?

**Comment by yuhr** [comment]
I'm not familiar with MongoDB, but as far as I can tell according to the [documentation](https://www.mongodb.com/docs/manual/reference/method/ObjectId/), it's binary format that you need to parse by yourself, as `runtypes` doesn't understand binary data.

I don't know what you exactly mean by “check”, but if you want to ensure that a given 12-byte data is truly meant to be `ObjectId`, the only option would be to ask the sender of the data to wrap the bytes by some tag, like `{ tag: "ObjectId", payload: "507f1f77bcf86cd799439011" }` and test it by `Record({ tag: Literal("ObjectId"), payload: String })`, since the format is not self-descriptive i.e. it does not contain some kind of “magic bytes” to identify itself is an `ObjectId`.

**Comment by 205g0** [comment]
Thanks, just checking if instanceof ObjectId would be enough, also I would like to keep it like it is and not transformed to a string

**Comment by yuhr** [comment]
Oh sorry, then `InstanceOf` runtype is exactly what you want. Going to add to the documentation. Thanks!
