### ISSUE TITLE
How do I define an array which is optional yet in case it was defined it shouldn't be empty ? 

### ISSUE THREAD

**Issue by AhmedMagedElhawary** [pelotom/runtypes#340]
I would have expected below to work

```
const optionalOrNonEmptyArray = t.Record({
  x: t
    .Array(t.Number)
    .optional()
    .withConstraint(
      (x) =>
        !x || x.length > 0 || ' Array size should be greater than zero',
    ),
});
```

But it is giving me "Expected array | undefined, but was missing" during my manual testing, any clue please ?

**Comment by yuhr** [comment]
Order matters. `.optional()` shorthand must come at the last. Following should work:

```typescript
const optionalOrNonEmptyArray = t.Record({
  x: t
    .Array(t.Number)
    .withConstraint(
      (x) =>
        x.length > 0 || ' Array size should be greater than zero',
    )
    .optional(),
});
```

This is due to the fact that `Record` treats its properties as optional only if they're wrapped within `Optional` runtype *at the outmost level*. It might technically be possible to support “bubbling up” of this optionality, but I just didn't want to make type inference complex further, as we always suffer from the type instantiation limit (<https://github.com/pelotom/runtypes/issues/212>).

**Comment by AhmedMagedElhawary** [comment]
Thank you so much for this great help, apologies I am new to the library, Tested out and you are right
