### ISSUE TITLE
Support for optional properties

### ISSUE THREAD

**Issue by MBuFD** [pelotom/runtypes#40]
Suggestion : support for optional properties on Record

- _.check_ would succeed if the optional properties are not present on the input object
- the inferred static type would have the optional properties denoted by the _?_ sign. 

Use case : _OpenAPI_ schemas and _Typescript_ support optional properties, thus such support in _runtypes_ would help in handling request bodies on Web api calls. Same for JSON data coming from no-SQL databases, where all fields are not always present.

**Comment by pelotom** [comment]
This can be accomplished by intersecting a `Record` with a `Partial`, e.g.

```ts
const Foo = Record({
  // Required properties:
  x: Number,
}).And(Partial({
  // Optional properties:
  y: String,
  z: Boolean,
}))
```

**Comment by MBuFD** [comment]
Great, thank you! Indeed this works for optional properties.

Remark: I ran into a small problem with constraints, where the error message issued is always _"No alternatives were matched"_ when the constraint is in the Partial (but same is ok if the Record), such as in the following example :  
```
export const PersonModel = Record({
    // Required properties: 
    name: String
}).And(Partial({
    // Optional properties:
    age: Number.withConstraint(age => (age >= 18) || `Sorry, your age is ${age} but you have to be 18 or over` )
}));
```
Remark: also, in the above example I had to use import _Intersect2_ and _Constraint_ for this to compile, when I use an _export_ on the Record.

**Comment by pelotom** [comment]
> Remark: I ran into a small problem with constraints, where the error message issued is always "No alternatives were matched" when the constraint is in the Partial (but same is ok if the Record), such as in the following example :

Yeah, currently `Partial` uses a union to check the value type at a given key:

https://github.com/pelotom/runtypes/blob/eea08aa5aaa5d3623342d699cb8fbda3001120d4/src/types/partial.ts#L25

which would be fine if `Union` gave more descriptive error messages. [This issue](https://github.com/pelotom/runtypes/issues/10) would address that.

> Remark: also, in the above example I had to use import Intersect2 and Constraint for this to compile, when I use an export on the Record.

I would guess this is because your compilation is set up to produce a declaration file (`"declaration": true`) and you're hitting [this quirk of TypeScript](https://github.com/Microsoft/TypeScript/issues/9944)?

**Comment by MBuFD** [comment]
Thank you, I'll comment under [issue #10](https://github.com/pelotom/runtypes/issues/10) if I have more to add about the validations and error messages.

Your guess was right, I removed `"declaration": true` from my tsconfig and indeed that fixed the problem with having to import Intersect2 and Union. ;) Thanks!

**Comment by virtulis** [comment]
Hi. Is there any rationale for not treating missing `Record` keys as `void` in the first place?

After all, if the type does not allow `void`, it will not match anyway but then `Union(Void, T)` could be used instead of `Record.And(Partial)`, which I think is not particularly straightforward.

In other words, I don't see what could break if the `hasKey` check was removed. What do you think?

**Comment by pelotom** [comment]
@virtulis I'm afraid I'm not really understanding what you're proposing. Could you give a more elaborate code example?
