### ISSUE TITLE
Usage with moment.js

### ISSUE THREAD

**Issue by gavinwahl** [pelotom/runtypes#86]
I'm trying to convert this type to runtypes:

```
import { Moment } from 'moment';
type Test {
    foo: Moment;
};
```

When I try to convert it to 
```
const Test = Record({
    foo: Moment,
});
```

I get `error: 'Moment' only refers to a type, but is being used as a value here.`. What's the correct way to encode this in runtypes?

**Comment by pelotom** [comment]
The idea is that you build up runtime representations of types which are then converted to static types. `Moment` in your example is a static type, so it can't be used directly in a runtime type. In order to validate that an object is of type `Moment` you need to use the [`isMoment` type guard](https://momentjs.com/docs/#/query/is-a-moment/) provided with that library. There is a [forthcoming feature](https://github.com/pelotom/runtypes/pull/78) which will allow you to use such a type guard to define a Runtype, like so:

```ts
import { isMoment } from 'moment';

const Test = Record({
    foo: Unknown.withGuard(isMoment),
});
```

This should be available soon, stay tuned!

**Comment by gavinwahl** [comment]
I ended up switching to io-ts because I need to convert from a string and would have needed two copies of most of my types otherwise. 

```typescript
const Moment = new t.Type<MomentType, string, unknown>(
  'MomentFromString',
  (u): u is MomentType => u instanceof moment,
  (u, c) =>
    t.string.validate(u, c).chain(s => {
      const m = moment(s, moment.ISO_8601, true);
      return m.isValid() ? t.success(m) : t.failure(u, c)
    }),
  a => a.toISOString(),
);
```

This library was much simpler to get started with but the conversion io-ts gives you is pretty convenient once you understand it.
